name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: withastro/action@v5
        env:
          PUBLIC_WATCHNO_INGEST_URL: https://api.watchnocode.noematic.eu/ingest
          PUBLIC_WATCHNO_API_KEY: ${{ secrets.WATCHNO_API_KEY }}
          PUBLIC_WATCHNO_PROJECT_ID: ${{ secrets.WATCHNO_PROJECT_ID }}
          PUBLIC_WATCHNO_SCRIPT_URL: https://qi.noematic.eu/watchno.min.js

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5